# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: "HHN8A6525R",
      issuer_id: "f04c51a5-7cf5-408e-b282-8a6f748591d5",
      key_filepath: "./certificates/AuthKey_HHN8A6525R.p8",
      duration: 1200,
      in_house: false
    )
    increment_build_number
    gym
    upload_to_testflight(
      app_identifier: "xyz.plhh.ByteCoin",
      api_key: api_key,
      ipa: "./ByteCoin.ipa",
      # skip_waiting_for_build_processing: true,
      skip_submission:true
    )
  end

  lane :screenshots do
    capture_ios_screenshots
    # upload_to_testflight
  end
end
